version: "3.7"
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - PORT=3001
      - DATABASE_URL=mysql://root:admin@db:3306/expense_tracker

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=expense_tracker
      - MYSQL_USER=mysql_user
      - MYSQL_PASSWORD=admin123
      - MYSQL_INITDB_SKIP_TZINFO=true
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
